#!/bin/sh
for host in  dev-gcp-db04
do
  echo "================================ Disc Capacity for $host ================================="
  ssh -i  ${HOME}/.ssh/dev_gcpchef01.pem dev_gcpchef01@$host "df -h"
  ssh -i  ${HOME}/.ssh/dev_gcpchef01.pem dev_gcpchef01@$host "sh /home/dev_gcpchef01/.mail/mail.sh"
  echo "================================================================================================="
  echo "                                                                                          "
done
